//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamo.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynamo.Common.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamo Boekingssysteem.
        /// </summary>
        public static string ApplictatieNaam {
            get {
                return ResourceManager.GetString("ApplictatieNaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betalingen.
        /// </summary>
        public static string Betalingen {
            get {
                return ResourceManager.GetString("Betalingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string ButtonAanmelden {
            get {
                return ResourceManager.GetString("ButtonAanmelden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        public static string ButtonAnnuleren {
            get {
                return ResourceManager.GetString("ButtonAnnuleren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bands.
        /// </summary>
        public static string ButtonBands {
            get {
                return ResourceManager.GetString("ButtonBands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheerders.
        /// </summary>
        public static string ButtonBeheerders {
            get {
                return ResourceManager.GetString("ButtonBeheerders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berichten.
        /// </summary>
        public static string ButtonBerichten {
            get {
                return ResourceManager.GetString("ButtonBerichten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betalen.
        /// </summary>
        public static string ButtonBetalen {
            get {
                return ResourceManager.GetString("ButtonBetalen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change log.
        /// </summary>
        public static string ButtonChangeLog {
            get {
                return ResourceManager.GetString("ButtonChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesloten dagen.
        /// </summary>
        public static string ButtonGeslotenDagen {
            get {
                return ResourceManager.GetString("ButtonGeslotenDagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidentele bands.
        /// </summary>
        public static string ButtonIncidenteleBands {
            get {
                return ResourceManager.GetString("ButtonIncidenteleBands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logboek.
        /// </summary>
        public static string ButtonLogboek {
            get {
                return ResourceManager.GetString("ButtonLogboek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo&apos;s.
        /// </summary>
        public static string ButtonMemos {
            get {
                return ResourceManager.GetString("ButtonMemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw.
        /// </summary>
        public static string ButtonNieuw {
            get {
                return ResourceManager.GetString("ButtonNieuw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw contract.
        /// </summary>
        public static string ButtonNieuwContract {
            get {
                return ResourceManager.GetString("ButtonNieuwContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samenvoegen.
        /// </summary>
        public static string ButtonOntdubbelen {
            get {
                return ResourceManager.GetString("ButtonOntdubbelen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        public static string ButtonOpslaan {
            get {
                return ResourceManager.GetString("ButtonOpslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        public static string ButtonPlanning {
            get {
                return ResourceManager.GetString("ButtonPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schermkleuren.
        /// </summary>
        public static string ButtonSchermkleuren {
            get {
                return ResourceManager.GetString("ButtonSchermkleuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluiten.
        /// </summary>
        public static string ButtonSluiten {
            get {
                return ResourceManager.GetString("ButtonSluiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systeeminstellingen.
        /// </summary>
        public static string ButtonSysteemInstellingen {
            get {
                return ResourceManager.GetString("ButtonSysteemInstellingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergoedingen.
        /// </summary>
        public static string ButtonVergoedingen {
            get {
                return ResourceManager.GetString("ButtonVergoedingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderen.
        /// </summary>
        public static string ButtonVerwijderen {
            get {
                return ResourceManager.GetString("ButtonVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volgende.
        /// </summary>
        public static string ButtonVolgende {
            get {
                return ResourceManager.GetString("ButtonVolgende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorige.
        /// </summary>
        public static string ButtonVorige {
            get {
                return ResourceManager.GetString("ButtonVorige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekoverzicht.
        /// </summary>
        public static string ButtonWeekOverzicht {
            get {
                return ResourceManager.GetString("ButtonWeekOverzicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lezen/Wijzigen.
        /// </summary>
        public static string ButtonWijzigen {
            get {
                return ResourceManager.GetString("ButtonWijzigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinsdag.
        /// </summary>
        public static string DagDinsdag {
            get {
                return ResourceManager.GetString("DagDinsdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donderdag.
        /// </summary>
        public static string DagDonderdag {
            get {
                return ResourceManager.GetString("DagDonderdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maandag.
        /// </summary>
        public static string DagMaandag {
            get {
                return ResourceManager.GetString("DagMaandag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijdag.
        /// </summary>
        public static string DagVrijdag {
            get {
                return ResourceManager.GetString("DagVrijdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woensdag.
        /// </summary>
        public static string DagWoensdag {
            get {
                return ResourceManager.GetString("DagWoensdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaterdag.
        /// </summary>
        public static string DagZaterdag {
            get {
                return ResourceManager.GetString("DagZaterdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zondag.
        /// </summary>
        public static string DagZondag {
            get {
                return ResourceManager.GetString("DagZondag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string MaandApril {
            get {
                return ResourceManager.GetString("MaandApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augustus.
        /// </summary>
        public static string MaandAugustus {
            get {
                return ResourceManager.GetString("MaandAugustus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string MaandDecember {
            get {
                return ResourceManager.GetString("MaandDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Februari.
        /// </summary>
        public static string MaandFebruari {
            get {
                return ResourceManager.GetString("MaandFebruari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Januari.
        /// </summary>
        public static string MaandJanuari {
            get {
                return ResourceManager.GetString("MaandJanuari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juli.
        /// </summary>
        public static string MaandJuli {
            get {
                return ResourceManager.GetString("MaandJuli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juni.
        /// </summary>
        public static string MaandJuni {
            get {
                return ResourceManager.GetString("MaandJuni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maart.
        /// </summary>
        public static string MaandMaart {
            get {
                return ResourceManager.GetString("MaandMaart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mei.
        /// </summary>
        public static string MaandMei {
            get {
                return ResourceManager.GetString("MaandMei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string MaandNovember {
            get {
                return ResourceManager.GetString("MaandNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktober.
        /// </summary>
        public static string MaandOktober {
            get {
                return ResourceManager.GetString("MaandOktober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string MaandSeptember {
            get {
                return ResourceManager.GetString("MaandSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geselecteerde band verwijderen?.
        /// </summary>
        public static string QuestionBandVerwijderen {
            get {
                return ResourceManager.GetString("QuestionBandVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geselecteerde beheerder verwijderen?.
        /// </summary>
        public static string QuestionBeheerderVerwijderen {
            get {
                return ResourceManager.GetString("QuestionBeheerderVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het geselecteerde bericht verwijderen?.
        /// </summary>
        public static string QuestionBerichtVerwijderen {
            get {
                return ResourceManager.GetString("QuestionBerichtVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gesloten periode verwijderen?.
        /// </summary>
        public static string QuestionGeslotenVerwijderen {
            get {
                return ResourceManager.GetString("QuestionGeslotenVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het geselecteerde item verwijderen?.
        /// </summary>
        public static string QuestionItemVerwijderen {
            get {
                return ResourceManager.GetString("QuestionItemVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geselecteerde memo verwijderen?.
        /// </summary>
        public static string QuestionMemoVerwijderen {
            get {
                return ResourceManager.GetString("QuestionMemoVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geselecteerde vergoeding verwijderen?.
        /// </summary>
        public static string QuestionVergoedingVerwijderen {
            get {
                return ResourceManager.GetString("QuestionVergoedingVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal openstaand bedrag: .
        /// </summary>
        public static string TotaalOpenstaand {
            get {
                return ResourceManager.GetString("TotaalOpenstaand", resourceCulture);
            }
        }
    }
}
